In [34]:
import numpy as np

In [35]:
hkl_demo = np.array([0,0,1])
uvw_demo = np.array([1,0,0])
ab_demo = np.array([1,0])

In [36]:
def x1matrix(hkl: np.ndarray, uvw: np.ndarray, ab: np.ndarray):
    uvw_prim = np.cross(hkl, uvw)
    # print(uvw_prim)
    x1 = np.zeros((3,3), dtype=float)
    x1[0,:]=ab[0] * uvw - ab[1] * uvw_prim
    x1[1,:]=ab[1] * uvw + ab[0] * uvw_prim
    x1[2] = hkl
    return x1

x1_demo = x1matrix(hkl_demo, uvw_demo, ab_demo)
print(x1_demo)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
def matrix_A(alpha):
    A = np.array([
        [np.cos(alpha), 0, -np.sin(alpha)],
        [0, 1, 0],
        [np.sin(alpha), 0, np.cos(alpha)]
    ])
    return A

def matrix_B(beta):
    B = np.array([
        [1, 0, 0],
        [0, np.cos(beta), -np.sin(beta)],
        [0, np.sin(beta), np.cos(beta)]
    ])
    return B

alpha1_demo = 0
beta1_demo = 0
A1_demo = matrix_A(alpha=alpha1_demo)
B1_demo = matrix_B(beta1_demo)
print(A1_demo)
print(B1_demo)

[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


In [38]:
def U_matrix(A, B, X):
    AB = np.matmul(A, B)
    U = np.matmul(AB.transpose(), X)
    return U

U_demo = U_matrix(A1_demo, B1_demo, x1_demo)
# print(AB1_demo)
print(U_demo)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
hkl2_demo = np.array([0,1,0])
x2_demo = x1matrix(hkl2_demo, uvw_demo, ab_demo)
print(x2_demo)

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


In [40]:
AB2_demo = np.matmul(x2_demo, U_demo.transpose())
print(AB2_demo)

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


In [41]:
def barely_equal(a, b, threshold):
    sub = a - b
    # print(sub)
    distance = (sub*sub).sum()
    # print(distance)
    if distance < threshold:
        return True
    else:
        return False

def ab_from_matrix(AB_mat, threshold):
    alpha = np.arcsin(-AB_mat[0,2])
    beta = np.arcsin(AB_mat[2,1])
    # check matrix part
    cosa, sina = np.cos(alpha), np.sin(alpha)
    cosb, sinb = np.cos(beta), np.sin(beta)
    check_matrix = np.matmul(matrix_A(alpha), matrix_B(beta))
    if not barely_equal(AB_mat, check_matrix, threshold):
        print("AB_mat:")
        print(AB_mat)
        print("check_matrix")
        print(check_matrix)
    return alpha, beta
    
alpha2_demo, beta2_demo = ab_from_matrix(AB2_demo, threshold=1.0)
print(alpha2_demo, beta2_demo)

-0.0 1.5707963267948966


In [42]:
!pip list

Package                 Version
----------------------- ---------
anyio                   3.5.0
appnope                 0.1.2
argon2-cffi             21.3.0
argon2-cffi-bindings    21.2.0
asttokens               2.0.5
attrs                   23.1.0
backcall                0.2.0
beautifulsoup4          4.12.2
bleach                  4.1.0
boltons                 23.0.0
brotlipy                0.7.0
certifi                 2023.7.22
cffi                    1.15.1
charset-normalizer      2.0.4
comm                    0.1.2
conda                   23.9.0
conda-content-trust     0.2.0
conda-libmamba-solver   23.9.1
conda-package-handling  2.2.0
conda_package_streaming 0.9.0
contourpy               1.0.5
cryptography            41.0.3
cycler                  0.11.0
debugpy                 1.6.7
decorator               5.1.1
defusedxml              0.7.1
entrypoints             0.4
executing               0.8.3
fastjsonschema          2.16.2
fonttools               4.25.0
idna                